version: '3.9'

services:
  api_service:
    build: ./api_service
    container_name: api_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    env_file:
      - ./api_service/.env 
    volumes:
      - ./api_service:/app
    depends_on:
      - redis

  meta_service:
    build: ./meta_service
    container_name: meta-service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./meta_service/.env 
    volumes:
      - ./meta_service:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: ./api_service
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./api_service:/app
    depends_on:
      - redis
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
