# Generated by Django 5.2.7 on 2025-10-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="image name", max_length=250
                    ),
                ),
                (
                    "google_drive_id",
                    models.CharField(
                        blank=True,
                        help_text="google drive ID",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True, help_text="file size(bytes)", null=True
                    ),
                ),
                ("mime_type", models.CharField(max_length=250)),
                ("storage_path", models.URLField(db_index=True, help_text="S3 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
